### ISSUE TITLE
Mistake on using ForeignKey attribute

### ISSUE THREAD

**Issue by ratanparai** [techcombd/asset-manager#10]
You have used `ForeignKey` attribute in wrong way in all of your `Entities`. Example -

```csharp
        [ForeignKey("AssetId")]
        public int AssetId { get; set; }
        public virtual Asset Asset { get; set; }
```

which should be -

```csharp
        [ForeignKey("Asset")]
        public int AssetId { get; set; }

        public virtual Asset Asset { get; set; }
```

For more information check [Creating a More Complex Data Model for an ASP.NET MVC Application](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-a-more-complex-data-model-for-an-asp-net-mvc-application)'s `ForeignKey` attribute use

**Comment by kajal-alpha** [comment]
Hi @ratanparai ,
Thanks for your feedback. i will fix this issue in next PR.
