### ISSUE TITLE
Automating code deployment with GitHub and Azure

### ISSUE THREAD

**Issue by mahedee** [techcombd/asset-manager#14]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Deployment
</code></pre>

## Expected behavior

Application will deployment to azure automatically after each push

## What is the motivation / use case for changing the behavior?

Currently, application is deployed to azure. But it does not work properly. 

## Help
https://blog.github.com/2015-09-15-automating-code-deployment-with-github-and-azure/

**Comment by ratanparai** [comment]
As I do not have `Azure` account, I can not help you in this issue. 

Adding `help wanted` label

**Comment by mahedee** [comment]
Published successfully. But there is an issue #30 need to resolve.
