### ISSUE TITLE
Modify dashboard

### ISSUE THREAD

**Issue by mahedee** [techcombd/asset-manager#15]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Dashboard is clean and blank in this moment.

## Expected behavior

There should some useful information or icon of useful information or frequent used information.

## What is the motivation / use case for changing the behavior?

Dashboard should not blank. Should have common information.

**Comment by kajal-alpha** [comment]
Hi @mahedee Bhai,
Please check following three free, open source, Bootstrap admin theme and choose one. my choice first one.

1. [AdminLTE](https://github.com/almasaeed2010/AdminLTE/releases)
2. [gentelella](https://github.com/puikinsh/gentelella)
3. [startbootstrap-sb-admin](https://github.com/BlackrockDigital/startbootstrap-sb-admin)

**Comment by mahedee** [comment]
So, I think we should go for number 1 if it has proper documentation

**Comment by kajal-alpha** [comment]
Hi @mahedee bhai,
we can use [ThemeWagon Star Admin - Super Responsive Free Bootstrap 4 Admin Dashboard Template](https://themewagon.com/themes/free-bootstrap-4-admin-dashboard-template-download/)

**Comment by kajal-alpha** [comment]
we can use this one also.
[Sufee HTML5 Admin Dashboard Template](https://github.com/puikinsh/sufee-admin-dashboard)

**Comment by ratanparai** [comment]
> we can use this one also.
[Sufee HTML5 Admin Dashboard Template](https://github.com/puikinsh/sufee-admin-dashboard)

Although every theme looks similar to me ( I am not a good designer 😉 ) , I like this one

**Comment by kajal-alpha** [comment]
This one also looks good... 
[ElaAdmin](https://github.com/puikinsh/ElaAdmin)
