### ISSUE TITLE
Delete unnecessary branches

### ISSUE THREAD

**Issue by ratanparai** [techcombd/asset-manager#20]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
</code></pre>

## Current behavior

There are lot of unnecessary branches. 

## Expected behavior

Every `PR` should be from different branch and after `Merging` the `PR` you should delete that branch. To do so click the <kbd>Delete branch</kbd> button. 

Example - 
Go to PR #18 and `see` there is a button named <kbd>Delete branch</kbd> before the comment box in the bottom. you should `press` this button every time you `merge` PR.  

## What is the motivation / use case for changing the behavior?

Unnecessary information is evil. If changes from any branch is already merged to the `master` bannch then there is no need for the branch to exists. So `delete` it and save the world

**Comment by kajal-alpha** [comment]
Delete done unnecessary Branch. close #20
