### ISSUE TITLE
remove commented out codes

### ISSUE THREAD

**Issue by ratanparai** [techcombd/asset-manager#3]
Do not keep commented out code. If you do not want/need this code then remove it.

**Comment by ratanparai** [comment]
@kajal-alpha:  If you are using `Visual Studio` as your `IDE` then you can use [SonarLint](https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2017) plugin for detecting potential code issues

**Comment by kajal-alpha** [comment]
Hi @ratanparai,
I'm using SonarLint now and it's working well.
