### ISSUE TITLE
Need to add Category information

### ISSUE THREAD

**Issue by aftabkajal** [techcombd/asset-manager#35]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently there is no Catagory user interface.

## Expected behavior

There should be an user interface to adding Catagory.

**Comment by kajal-alpha** [comment]
Category added.
