### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by ratanparai** [techcombd/asset-manager#4]
CI integration for automatic build on push chage

**Comment by ratanparai** [comment]
I can do this `Integration`  @kajal-alpha if you want. Should I use `CI` integration like [Academia](https://github.com/techcombd/academia) ? What do you think @mahedee ?

**Comment by kajal-alpha** [comment]
Hi @ratanparai, 
you can add CI integration for this project. I think it would be better.

**Comment by ratanparai** [comment]
Ok. I will add it tomorrow and send PR
